### ISSUE TITLE
1.9 help

### ISSUE THREAD

**Issue by Omri100** [DieReicheErethons/Brewery#111]
The plugin is working but it appears the actual brews are missing the textures.
Is it caused by the switch to NBT to determine potion color?
http://i.imgur.com/Z8zBkBc.png

**Comment by Feuerstern** [comment]
Yes, it is. Potions work entirely different in 1.9, so it's kind of hard and hacky to update Brewery. You're probably also getting problems with potion effects. I'm working on it, though :)

**Comment by Sn0wStorm** [comment]
Hey,
i'll be active here again from now on and can be working on problems with this Plugin. Im sorry i was so inactive, ive been checking on the plugin and it seemed to be working kind of ok. Now with 1.9 there probably needs to be some changes.

Feuerstern im glad you took on the update, is it a lot of work to do for 1.9? if so we may need to do a full rework on the potions, like how they are saved and everything and completely try to use NBT data.  
Thanks!

**Comment by Feuerstern** [comment]
The problem is that in 1.9, a potion always has a main potion effect which determines the color. If there is none, the potion gets a placeholder texture. Up to 1.8, Brewery used to use colored potions without any effects. The only possible way I could think of to get it to work was to use a listener to set the main effect to null when the PlayerItemConsumeEvent is triggered and the item is a Brewery potion. This solution is kind of working, even though I'm getting errors because null seems to be invalid for PotionMeta#setMainEffect(). Wb :)

**Comment by Sn0wStorm** [comment]
Plugin has been updated to 1.9
