### ISSUE TITLE
factions 2.8.7 integration

### ISSUE THREAD

**Issue by GoadingGoat** [DieReicheErethons/Brewery#118]
Would you consider adding protection of the barrels using factions 2.8.7? ( if it's even possible)

**Comment by Sataniel98** [comment]
Is definitely possible, but I'd rather suggest to use https://github.com/MarkehMe/FactionsFramework by MarkehMe instead of directly accessing the Factions API. The advantage is that it will also support different versions of Factions like 1.6.9.5 / FactionsUUID, 1.8.2 / FactionsOne, 2.6 and upcoming versions without any modifications.

**Comment by Sn0wStorm** [comment]
Is it possible to open Barrels in Factions that you should not be opening? So Factions does not cancel the Interact Event?
