### ISSUE TITLE
SUpport for Kingdoms+

### ISSUE THREAD

**Issue by renzotom** [DieReicheErethons/Brewery#129]
Please add support for plugin Kingdoms+, maybe if you ask author, he give you copy.
https://www.spigotmc.org/resources/kingdoms-battle-for-land-might-and-glory-1-8-x-1-9.11833/

**Comment by Sn0wStorm** [comment]
What exactly should i add support for? Opening barrels in kingdoms or what?

If the plugin is coded so that it cancels interactions then it should work as is and Players can not open barrels if the interaction is cancelled.

I dont know if it would be easily possible to add support for that as the source code is not available

**Comment by renzotom** [comment]
I mean opening barrels in kingdom, but thanks me for answer. I now think, what you  mean (If the plugin is coded so that it cancels interactions then it should work as is and Players can not open barrels if the interaction is cancelled.)

**Comment by Sn0wStorm** [comment]
There is no source, would be way too annoying to add support for that. I would need a public maven repo as well. So wont be doing that.

Ill be adding an api to Brewery so they could add support.
