### ISSUE TITLE
Duplicate Chat Messages

### ISSUE THREAD

**Issue by CKGAR** [DieReicheErethons/Brewery#133]
When clicking on a cauldron with a clock, or doing any Brewery action really, it sends two of the same message in chat. No errors in console. This is in the latest build you linked on GitHub #130 

Example:
![image](https://cloud.githubusercontent.com/assets/8227387/16208186/e9254070-36fe-11e6-8688-73332853c604.png)

I wish you had a place you released dev builds, because I am sure many of us would be willing to help you test and find bugs faster. It would also cut times in between official releases.

**Comment by Sn0wStorm** [comment]
Thanks 
Yes this is the same problem as #132 
Will be fixed in the next commit. 

As for dev builds, you can clone or download this repo and do "mvn clean install" to get the compiled plugin. 
Ill see if i can get dev builds hosted somewhere, but often dev builds can break stuff and not work, etc. So using the latest dev build is not recommended

**Comment by Sn0wStorm** [comment]
Fixed, see #132

**Comment by CKGAR** [comment]
Awesome! Thank you for your continued development of Brewery, it's a really unique plugin and my players absolutely love it. Hope to see new features getting added!

**Comment by Sn0wStorm** [comment]
Right now I am working on some more bug fixes, new features are also being developed in this branch for now: 
https://github.com/DieReicheErethons/Brewery/tree/2.0-StoreDataInLore
