### ISSUE TITLE
About the last step Aging

### ISSUE THREAD

**Issue by AcFox97** [DieReicheErethons/Brewery#244]
No matter what formula I use, it's always liquid waste qwq

**Comment by Goncorer** [comment]
I was having this problem. From what I can tell, the drink spoils if you open the barrel before it's done ageing.
You have to leave it sealed until the right number of days have passed, and I _think_ it stops ageing when you open the barrel, but idk it might just be that it turns into ruined potion if it's opened too soon.
Hope that helps, otherwise it is actually a bug

**Comment by Sn0wStorm** [comment]
You should definitely be able to leave it in a barrel or put it back and it should be fine when it is done aging.
If you open and close the barrel, you might have to leave it alone for a few minutes for the drinks inside to update and keep aging

**Comment by Sn0wStorm** [comment]
This might be the same as #235
