### ISSUE TITLE
help needed with adding effects to potions

### ISSUE THREAD

**Issue by mcgodbuild** [DieReicheErethons/Brewery#272]
I've been looking at the effects you can add to the potions like the haste you get from the hot choco.

I was just wondering if anyone can explain to me how to set it up? I dont want every potion to have the same effects, but i dont know how the effects are calculated either. Some more info of a wiki page would be helpfull i think.

**Comment by Sn0wStorm** [comment]
Find the effect you want on https://hub.spigotmc.org/javadocs/spigot/org/bukkit/potion/PotionEffectType.html
For Example SPEED. Then you need to know which level and duration you want, lets say you want level 1 and 30 seconds at the worst potion quality and level 2 and 40 seconds at the best potion quality.
So that makes SPEED/1-2/30-40
All outcomes of potions in between worst and best are just taking values in between what you configured.

**Comment by mcgodbuild** [comment]
ahh i see so thats how you set it up, ty that makes a lot more sense now
