### ISSUE TITLE
Custom Brews not working at all, including the ones commented out after being uncommented

### ISSUE THREAD

**Issue by CtrlAltElitist** [DieReicheErethons/Brewery#303]
I cant get any of them to work. At this point I'm suspecting its my file editor of choice. I'm remoting in to a linux server where my MC server is running from, and I'm using the built in Vim editor. I made sure alignment and spaces were accurate. all i did was remove the comments from something like Fire Whiskey, and even that did not work.. I'm at a complete loss.

**Comment by LeeSpork** [comment]
Are you sure you're editing the correct file? e.g. `brewery/config.yml` and not `brewery/configs/en/config.yml`

**Comment by Kbryst** [comment]
Download the file and try it with like notepad++ or something. I hear this a million times from my staff, their files don't save or they just "can't figure out why this part works but I like just removed it but its still here I don't get it". 

Make sure you restart instead of reload. I've personally not seen any issues with the reload of this plugin, but my general rule is "rule out the stupid first".

**Comment by CtrlAltElitist** [comment]
I figured out that it was a weird quirk with my instance. The file wasn’t being saved properly or was being overwritten. I think I straightened it out. I have a few drinks working now. Thank you all so much.
