### ISSUE TITLE
Brews turning Murky or Ruined

### ISSUE THREAD

**Issue by Sn0wStorm** [DieReicheErethons/Brewery#335]
All Brews turn either to `Murky Distillate` or `Ruined Brew` in the Distiller or Barrel.

The issue seems to be that at some point the Brew data suddenly includes 0 ingredients.

Log:  
https://pastebin.com/CwNqbPHf  

The update 2.1.2 improves ingredient data handling, so that might fix the issue.

If the issue **still persists**, I need some more infos to reproduce it. If you have the distilling issue, please do these steps:  
1. Take a Brew from the Cauldron
2. Hold in Hand and do `/brew debuginfo` which will put info into the Server-Log
3. Distill and when it turns into Murky Distillate hold in hand und do `/brew debuginfo` again
4. Post the Server-Log of both commands here.

**Comment by Sn0wStorm** [comment]
Anyone with this problem, please try if this version fixes it.

[Brewery-2.1.3-DEV.zip](https://github.com/DieReicheErethons/Brewery/files/5505711/Brewery-2.1.3-DEV.zip)
Compiled from 3fa16414d0e002db18e36e6ecabe741b18de3651

**Comment by Imouto-Kaede** [comment]
Hi, 
Me and my friends have a server that we added this plugin into. We had the same issue.
Game version: 1.16.4
The fermentation turned out fine, I had e.g. boiled herbs but putting it into distilling (with or without blaze powder) turned it into a murky distillate. I also tried making normal beer, I was able to make fermented wheat, then I put it into a barrel and in the end it turned into a 1-year aged ruined potion. 
Some more info:
We added the plugin well after creating the world.
We run other plugins, here's a list: Vanish, Sleepy, InfinityMendingUnnerf, DeadChest, ArmoredEltyra, AntiVPN, AdvancedTeleport, TradePlus, GodAppleCrafting
I will try to provide debug info on:
Any fermented brew 
Any murky distillate
Any ruined potion
I will try to test all of these steps and results on both the 2.1.2 version and the devbuild you sent. I'll post all the debug info in my next comment.

**Comment by Imouto-Kaede** [comment]
The wine turned out fine, so I tried to age another drinks. They turned out fine too, so here is what I was able to get from fermented brews (sugar brew) and murky distillates (from the sugar brew). This is for the devbuild.
Pastebin link: https://pastebin.com/245MDFBu (will expire in 6 months)
Now, for the 2.1.2, After distilling a sugar brew, it turned into a murky distillate. I also got fermented wheat, and after aging I got fine beer.
Here is a link to pastebin: https://pastebin.com/8gWTpvC2 (will also expire in 6 months)

**Comment by Sn0wStorm** [comment]
Do you know why the drinks turn out fine now?

From what i can see in the logs, the sugar brews are turning into murky as expected, because you used 32 sugar cane and no recipe needs that much. I'm guessing it turns into rum correctly if you use 18 sugar cane?

**Comment by Imouto-Kaede** [comment]
Some people told that regenerating the config file by deleting it and reloading the server worked for them. We did that while reinstalling the plugins. I can provide more debug info from trying to distill gin, as it's a pretty straightforward recipe. If I understand right, you need to ferment it for 3-5 minutes? I fermented it for 5 minutes last time, and it turned into a murky distillate.

**Comment by Sn0wStorm** [comment]
@Imouto-Kaede  Gin in its default config needs 9 Wheat, 6 Cornflowers, 1 Apple. 6 Minutes Fermenting.


This issue is fixed in v3.0. If there still is only Murky or Ruined Brews, it is likely a different issue, in that case please report here.
