### ISSUE TITLE
Adding New Recipes

### ISSUE THREAD

**Issue by Schneiderism** [DieReicheErethons/Brewery#77]
I tried adding a recipe for Tequila using Blue Orchids, Melon, and Sugar Cane. When I loaded it up and tried adding melons and orchids to the cauldron, it wouldn't accept them. What am I doing wrong here?

   11:
      name: Poor Tequila/Tequila/Hard Tequila
      ingredients:
      - SUGAR_CANE/1
      - 38,1/3
      - 360/1
      cookingtime: 3
      distillruns: 6
      color: DARK_RED
      difficulty: 3
      alcohol: 25
      effects:
      - POISON/10-20
      - STRENGTH/20-40

In place of item ID for the orchid, I also tried "RED_FLOWER,1" 

Thanks for the help!

**Comment by Deiscorides** [comment]
The block that is grown is: melon_block or 103
The melon slices you get from a melon block is: melon or 360

-If you are using ID 360 and trying to add the melon_block to the cauldron then it won't work, use melon slices instead.
-It may also be how you did the ingredients in the "cooked:" list below all the recipes. Make sure it is properly done. All new ingredients you want to use need to be listed there.
-If you find that you can't put any ingredients into your cauldron,

1: The alignment of Number of the Recipe, is off by one space or more,
in relation to the rest of the recipes.
2: Make sure the recipes are numbered properly. If you accidentally
skip a number or copied and pasted without renumbering.
3: Make sure you don't leave out a word in the recipe like "effects:"
and still list types of effects under it.

Your ingredients in the "cooked:" section should look something like this with # comments to help you remember things:

WHEAT: Fermented wheat
SUGAR_CANE: Sugar brew
APPLE: Apple cider
POTATO_ITEM: Potatomash
RED_MUSHROOM: Mushroom brew
# Melon Slices,
103: Fruity Flavoring
# Flowers, not including 37 Yellow_flower or tall flowers,
38: Floral Note

**Comment by Annahstas** [comment]
# config for Brewery.jar


# -- Settings --
# Defaults are written in []
# Deleting of single settings disables them

# Languagefile to be used (found in plugins/Brewery/languages)
language: en

# If the player wakes up at /home when logging in after excessive drinking (/home plugin must be installed!) [true]
enableHome: true

# Type of the home-teleport: ['cmd: home']
# bed = Player will be teleported to his spawn bed
# SamplePlugin = installed home plugin. Supports: ManagerXL. If not available:
# 'cmd: home' = /home will be executed by the player. He has to have permissions for it without any delay!
# 'cmd: spawn' = /spawn will be executed by the player.
# 'cmd: whatever' = /whatever will be executed by the player.
homeType: 'cmd: home'

# If the player "wakes up" at a random place when offline for some time while drinking (the places have to be defined with '/br Wakeup add' through an admin)
# The Player wakes at the nearest of two random places of his world [true]
enableWake: true

# If the Player may get some logins denied, when his character is drunk [true]
enableLoginDisallow: true

# If the Player faints (gets kicked) for some minutes if he overdrinks [true]
enableKickOnOverdrink: true

# If the Player vomits on high drunkeness (drops item defined below) [true]
# The item can not be collected and stays on the ground until it despawns. (Warning: May be collected after Server restart!)
enablePuke: true

# Item that is dropped multiple times uncollectable when puking [SOUL_SAND]
pukeItem: SOUL_SAND

# Consumable Item/strength. Decreases the alcohol level by <strength> when consumed. (list)
drainItems:
- BREAD/4
- MILK_BUCKET/2

# Time (in days) that drunkeness-data stays in memory after a player goes offline, to apply hangover etc. [7]
hangoverDays: 7

# Color the Item information (lore) depending on quality while it is 1. in a barrel and/or 2. in a brewing stand [true, false]
colorInBarrels: true
colorInBrewer: false

# If a Large Barrel can be opened by clicking on any of its blocks, not just Spigot or Sign. This is always true for Small Barrels. [true]
openLargeBarrelEverywhere: true

# Enable checking for Updates, Checks the curseforge api for updates to Brewery [true]
# If an Update is found a Message is logged on Server-start and displayed to ops joining the game
updateCheck: true

# Autosave interval in minutes [3]
autosave: 3

# Config Version
version: '1.3.1'


# -- Recipes for Potions --

# name: Different names for bad/normal/good (Formatting codes possible: such as &6)
# ingredients: List of 'material or id,data/amount'
#   (Item-ids instead of material are deprecated by bukkit and may not work in the future!)
#   A list of materials can be found here: http://jd.bukkit.org/beta/apidocs/org/bukkit/Material.html
#   You can specify a data value, omitting it will ignore the data value of the added ingredient
# cookingtime: Time in real minutes ingredients have to boil
# distillruns: How often it has to be distilled for full alcohol (0=without distilling)
# wood: Wood of the barrel 0=any 1=Birch 2=Oak 3=Jungle 4=Spruce 5=Acacia 6=Dark Oak
# age: Time in Minecraft-days, the potion has to age in a barrel 0=no aging
# color: Color of the potion after distilling/aging.
#   Usable Colors: DARK_RED, RED, BRIGHT_RED, ORANGE, PINK, BLUE, CYAN, WATER, GREEN, BLACK, GREY, BRIGHT_GREY
# difficulty: 1-10 accuracy needed to get good quality (1 = unaccurate/easy, 10 = very precise/hard)
# alcohol: Absolute amount of alcohol 0-100 in a perfect potion (will be added directly to the player, where 100 means fainting)
# effects: List of effect/level/duration  Special potion-effect when drinking, duration in seconds.
#   Suffix name with 'X' to hide effect from label. Sample: 'POISONX/2/10' (WEAKNESS, INCREASE_DAMAGE, SLOW and SPEED are always hidden.)
#   Possible Effects: http://jd.bukkit.org/rb/apidocs/org/bukkit/potion/PotionEffectType.html
#   Level or Duration ranges may be specified with a "-", ex. 'SPEED/1-2/30-40' = level 1 and 30 sec at worst and lvl 2 and 40 sec at best
#   Ranges also work high-low, ex. 'POISON/3-1/20-5' for weaker effects at good quality.
#   Highest possible Duration: 1638 sec. Instant Effects dont need any duration specified.

recipes:
#  Example Recipe with every possible entry first:
   0:
      name: Bad Example/Example/Good Example
      ingredients:
      - SUGAR_CANE/5
      - 264/1
      - INK_SACK,3/20
      - 5,1/8
      cookingtime: 3
      distillruns: 2
      wood: 4
      age: 11
      color: DARK_RED
      difficulty: 3
      alcohol: 23
      effects:
      - FIRE_RESISTANCE/20
      - HEAL/1
      - WEAKNESS/2-3/50-60
      - POISONX/1-0/20-0
   1:
      name: Skunky Wheatbeer/Wheatbeer/Fine Wheatbeer
      ingredients: 
      - WHEAT/3
      cookingtime: 8
      distillruns: 0
      wood: 1
      age: 2
      color: BRIGHT_GREY
      difficulty: 1
      alcohol: 5
   2:
      name: Skunky Beer/Beer/Fine Beer
      ingredients: 
      - WHEAT/6
      cookingtime: 8
      distillruns: 0
      wood: 0
      age: 3
      color: ORANGE
      difficulty: 1
      alcohol: 6
   3:
      name: Skunky Darkbeer/Darkbeer/Fine Darkbeer
      ingredients: 
      - WHEAT/6
      cookingtime: 8
      distillruns: 0
      wood: 4
      age: 8
      color: BLACK
      difficulty: 2
      alcohol: 7
   4:
      name: Awkward Mead/Mead/&6Golden Mead
      ingredients: 
      - SUGAR_CANE/6
      cookingtime: 3
      distillruns: 0
      wood: 2
      age: 4
      color: ORANGE
      difficulty: 2
      alcohol: 9
   5:
      name: Apple Mead/Sweet Apple Mead/&6Sweet Golden Apple Mead
      ingredients: 
      - SUGAR_CANE/6
      - APPLE/2
      - WHEAT/3
      cookingtime: 4
      distillruns: 0
      wood: 2
      age: 4
      color: ORANGE
      difficulty: 4
      alcohol: 12
      effects:
      - WATER_BREATHINGX/1-2/150
   6:
      name: Bitter Rum/Spicy Rum/&6Golden Rum
      ingredients: 
      - SUGAR_CANE/14
      cookingtime: 5
      distillruns: 2
      wood: 2
      age: 14
      color: DARK_RED
      difficulty: 6
      alcohol: 30
      effects:
      - FIRE_RESISTANCE/1/20-100
      - POISONX/1-0/30-0
   7:
      name: Lousy Vodka/Vodka/Russian Vodka
      ingredients: 
      - POTATO_ITEM/10
      cookingtime: 15
      distillruns: 3
      age: 0
      color: BRIGHT_GREY
      difficulty: 4
      alcohol: 20
      effects:
      - WEAKNESS/15
      - POISON/10
   8:
      name: Poor Absinthe/Absinthe/Strong Absinthe
      ingredients:
      - LONG_GRASS/15
      cookingtime: 3
      distillruns: 6
      color: GREEN
      difficulty: 8
      alcohol: 45
      effects:
      - POISON/20-30
   9:
      name: Potato soup
      ingredients:
      - POTATO_ITEM/5
      - LONG_GRASS/3
      cookingtime: 3
      color: PINK
      difficulty: 1
      effects:
      - HEAL/0-1
   10:
      name: Stale Coffee/Coffee/Strong Coffee
      ingredients:
      - INK_SACK,3/12
      - MILK_BUCKET/2
      cookingtime: 2
      color: BLACK
      difficulty: 3
      effects:
      - REGENERATION/1/2-5
      - SPEED/1/30-140
   11:
      name: Atrocious Apple Juice/Acceptable Apple Juice/Phenomenal Apple Juice
      ingredients:
      - SUGAR/5
      - APPLE/10
      cookingtime: 1
      color: ORANGE
      difficulty: 1
      effects:
      - HEAL/1-3/1-10
   12:
      name: Apple Smoothie/Apple Smoothie/Apple Smoothie
      ingredients:
      - SUGAR_CANE/1
      - APPLE/2
      - SNOWBALL/2
      cookingtime: 1
      color: ORANGE
      difficulty: 1
      effects:
      - HEAL/1-3/1-10
# More Recipes ideas: Cachaca, Gin, Whiskey, Tequila, Cider, etc. as well as high quality abbreviations like golden vodka etc.
# I will not add more Recipes to the default config, as they would be public and viewable by users to cheat.
# It is up to the Serveradmin to change and add Recipes, so players cannot cheat from the default config.



# cooked: EVERY possible ingredient and the names for the originating potions after fermenting:
# [Example] MATERIAL_or_id: Name after cooking

cooked:
   WHEAT: Fermented wheat
   SUGAR_CANE: Sugar brew
   APPLE: Apple cider
   POTATO_ITEM: Potatomash
   LONG_GRASS: Boiled herbs
   RED_MUSHROOM: Mushroom brew
   INK_SACK: Colored brew
   MILK_BUCKET: Milky water
   SUGAR: Sweet Water
   SNOWBALL: Ice
   



# -- Plugin Compatibility --

# Enable checking of other Plugins (if installed) for Barrel Permissions [true]
useWorldGuard: true
useLWC: true
useGriefPrevention: true

# Enable the Logging of Barrel Inventories to LogBlock [true]
useLogBlock: true


# -- Chat Distortion Settings --

# Log to the Serverlog what the player actually wrote, before his words were altered [false]
logRealChat: false

# Text after specified commands will be distorted when drunk (list) [- /gl]
distortCommands:
- /gl
- /global
- /fl
- /s
- /letter
- /g
- /l
- /lokal
- /local
- /mail send
- /m
- /msg
- /w
- /whisper
- /reply
- /r

# Distort the Text written on a Sign while drunk [false]
distortSignText: false

# Enclose a text with these Letters to bypass Chat Distortion (Use "," as Separator) (list) [- '[,]']
distortBypass:
- '*,*'
- '[,]'

# words: Words and letters that will be altered when chatting while being drunk.
# Will be processed from first to last and a written sentece is altered in that order.

# replace: Word or letter to be replaced. (Special: "-space": replaces space, "-random": insert into random position, "-all": everything, "-start": At Beginning, "-end": At the End.)
# to: What to replace it with.
# pre: Words and Letters before the wanted word (split with ",")
# match: true = one of the "pre"-Words has to be before the wanted Word,  false = none of the "pre" Words is allowed before the wanted Word
# alcohol: 1-100 minimum drunkeness after which this word ist replaced
# percentage: Probability of replacing a Word in percent

words:
-  replace: s
   to: sh
   percentage: 90
   alcohol: 30

-  replace: ch
   to: sh
   pre: u,s,o,a
   match: false
   alcohol: 10
   percentage: 70

-  replace: h
   to: hh
   pre: sch,h,t
   match: false
   percentage: 60
   alcohol: 20

-  replace: th
   to: thl
   percentage: 40
   alcohol: 30

-  replace: sch
   to: shk
   percentage: 60
   alcohol: 40

-  replace: u
   to: uuh
   percentage: 20

-  replace: y
   to: yy
   percentage: 60
   alcohol: 15

-  replace: e
   to: ee
   percentage: 40
   alcohol: 15

-  replace: you
   to: u
   percentage: 40

-  replace: u
   to: uo
   pre: u
   match: false
   percentage: 60

-  replace: that
   to: taht
   percentage: 20
   alcohol: 40

-  replace: p
   to: b
   percentage: 30

-  replace: p
   to: b
   percentage: 70
   alcohol: 60

-  replace: up
   to: ubb
   percentage: 80
   alcohol: 25

-  replace: o
   to: oh
   percentage: 20

-  replace: ei
   to: i
   percentage: 30
   alcohol: 15

-  replace: b
   to: bb
   percentage: 80
   alcohol: 40

-  replace: '!!!'
   to: '!!!111!!!eleven!1!'
   pre: '!'
   match: false
   percentage: 20
   alcohol: 70

-  replace: '!'
   to: '!!'
   pre: '!'
   match: false
   percentage: 90

-  replace: drunk
   to: dhrkunn
   pre: are
   match: false
   percentage: 70
   alcohol: 65

-  replace: walk
   to: whhealhk
   pre: you can, you can still, you can not
   match: false
   percentage: 80
   alcohol: 30

-  replace: wtf
   to: wft
   percentage: 20
   alcohol: 40

-  replace: lol
   to: loool
   percentage: 80
   alcohol: 10

-  replace: afk
   to: aafkayyy
   percentage: 30
   alcohol: 30

-  replace: write
   to: wreitt
   pre: you can,you can still,you can not
   match: false
   percentage: 80
   alcohol: 50

-  replace: drink
   to: booze
   percentage: 80
   alcohol: 70

-  replace: '?'
   to: '????'
   pre: '?'
   match: false
   percentage: 80
   alcohol: 40

-  replace: -space
   to: ''
   pre: h,g,w
   match: true
   alcohol: 10

-  replace: -space
   to: ''
   percentage: 30
   alcohol: 35

-  replace: -space
   to: ''
   percentage: 10

-  replace: -start
   to: dho
   percentage: 15
   alcohol: 50

-  replace: -start
   to: hhn
   percentage: 10
   alcohol: 50

-  replace: -random
   to: lu
   percentage: 10

-  replace: -random
   to: lug
   percentage: 10
   alcohol: 50

-  replace: -random
   to: blub
   percentage: 20
   alcohol: 80

-  replace: -random
   to: lerg
   percentage: 40
   alcohol: 85

-  replace: -random
   to: gul
   percentage: 40
   alcohol: 80

-  replace: -random
   to: ' '
   percentage: 100
   alcohol: 70

-  replace: -random
   to: ' '
   percentage: 60
   alcohol: 40

-  replace: -random
   to: ' '
   percentage: 50
   alcohol: 30

-  replace: -end
   to: '!'
   percentage: 40
   alcohol: 30

-  replace: -random
   to: ' *hic* '
   percentage: 80
   alcohol: 70

-  replace: -random
   to: ' *hic* '
   percentage: 15
   alcohol: 40

-  replace: -space
   to: ' *hic* '
   percentage: 5
   alcohol: 20

-  replace: -end
   to: ' *hic*'
   percentage: 70
   alcohol: 50

-  replace: -all
   to: '*burp*'
   percentage: 3
   alcohol: 60

-  replace: -all
   to: '*burp*'
   percentage: 6
   alcohol: 80


here is my whole code that I have. I have tried to add these two new recipes in the bottom numbers 11 and 12 and it is not working. The snowballs or the regular plain sugar is not adding itself to the game. I added them into cooked items and did the recipe correctly by what I see. Please help me figure out why it is not working. Thank you so much.

**Comment by Deiscorides** [comment]
@Annahstas 

It is difficult to see the proper format for your config in this type of posting. Being able to discern the spacing is also needed in finding out various bugs. Normally, it is better to upload the config.yml file then link it here. That way people that want to help will be able to help a bit better since they can spot spacing issues.

Are you getting error messages in your server console when it first starts with this config.yml file? If so, what are they specifically?

In regards to "snowball" I use the data value number for it.

In the recipe I use this (example of 9 snowballs being used):

      '#' SNOWBALL
      - 332/9

In the "cooked" section I use this,

   '#' SNOWBALL
   332: Shaved Ice

For SUGAR I just use the word "SUGAR".

The biggest problem I see with your new recipes is the short cooking time "cookingtime: 1". In all of my recipes (260 of them so far) I always have a cooking time of 3 minutes or longer. I found that things didn't work quite right when it was set lower than that. If you are not getting invalid ingredient errors in your console, try upping the cooking times to 3+ minutes.
